/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lokadata;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.lang.reflect.Array;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author fataelislami
 */
public class CaLo extends javax.swing.JFrame {

    /**
     * Creates new form CaLo
     */
    public CaLo() {
        initComponents();
        txtUsername.setPreferredSize(new Dimension(100,100));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        Top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegist = new javax.swing.JLabel();
        btnRegist1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        Login = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        txtPassword1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtUsername2 = new javax.swing.JTextField();
        txtPassword2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(231, 229, 227));

        Top.setBackground(new java.awt.Color(14, 27, 53));
        Top.setBorder(null);

        btnRegist.setForeground(new java.awt.Color(254, 254, 254));
        btnRegist.setText("Login");
        btnRegist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistMouseClicked(evt);
            }
        });

        btnRegist1.setForeground(new java.awt.Color(254, 254, 254));
        btnRegist1.setText("Register");
        btnRegist1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegist1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/PROJECT/Kuliah/OOP/JavaGUI/C.A.L.O.png")); // NOI18N

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLayout.createSequentialGroup()
                        .addGap(494, 494, 494)
                        .addComponent(jLabel1)
                        .addContainerGap(190, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegist1)
                        .addGap(30, 30, 30)
                        .addComponent(btnRegist)
                        .addGap(25, 25, 25))))
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(TopLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegist1)
                            .addComponent(btnRegist))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Body.setLayout(new java.awt.CardLayout());

        Login.setBackground(new java.awt.Color(231, 229, 227));
        Login.setForeground(new java.awt.Color(254, 254, 254));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setBackground(new java.awt.Color(231, 229, 227));
        txtUsername.setForeground(new java.awt.Color(1, 1, 1));
        txtUsername.setText("Username");
        txtUsername.setBorder(null);
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        Login.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 270, 30));
        Login.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 270, 20));
        Login.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 270, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/login.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        Login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        txtPassword.setBackground(new java.awt.Color(231, 229, 227));
        txtPassword.setText("jPasswordField1");
        txtPassword.setBorder(null);
        Login.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 270, 30));
        Login.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));
        Login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/Wellcome.png")); // NOI18N
        Login.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        Body.add(Login, "login");

        Register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/Wellcome.png")); // NOI18N
        Register.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        txtUsername1.setBackground(new java.awt.Color(231, 229, 227));
        txtUsername1.setForeground(new java.awt.Color(1, 1, 1));
        txtUsername1.setText("Email");
        txtUsername1.setBorder(null);
        txtUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername1ActionPerformed(evt);
            }
        });
        Register.add(txtUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 270, 30));

        txtPassword1.setBackground(new java.awt.Color(231, 229, 227));
        txtPassword1.setText("jPasswordField1");
        txtPassword1.setBorder(null);
        Register.add(txtPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 270, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/daftar.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        Register.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        txtUsername2.setBackground(new java.awt.Color(231, 229, 227));
        txtUsername2.setForeground(new java.awt.Color(1, 1, 1));
        txtUsername2.setText("Username");
        txtUsername2.setBorder(null);
        txtUsername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername2ActionPerformed(evt);
            }
        });
        Register.add(txtUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 270, 30));

        txtPassword2.setBackground(new java.awt.Color(231, 229, 227));
        txtPassword2.setText("jPasswordField1");
        txtPassword2.setBorder(null);
        Register.add(txtPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 270, 30));

        Body.add(Register, "register");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(Top, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistMouseClicked
        // TODO add your handling code here:
        CardLayout card=(CardLayout)Body.getLayout();
        card.show(Body,"login");
    }//GEN-LAST:event_btnRegistMouseClicked

    private void btnRegist1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegist1MouseClicked
        // TODO add your handling code here:
        CardLayout card=(CardLayout)Body.getLayout();
        card.show(Body,"register");
    }//GEN-LAST:event_btnRegist1MouseClicked

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        String username=txtUsername.getText();
        char[] password=txtPassword.getPassword();
        ArrayList<String> obj=new ArrayList();
        obj.add(username);
        
        new Home(obj).setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void txtUsername2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaLo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaLo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaLo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaLo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaLo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Register;
    private javax.swing.JPanel Top;
    private javax.swing.JLabel btnRegist;
    private javax.swing.JLabel btnRegist1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername1;
    private javax.swing.JTextField txtUsername2;
    // End of variables declaration//GEN-END:variables
}
