/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lokadata;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author fataelislami
 */
public class Home extends javax.swing.JFrame {
    

    

 
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    public Home(ArrayList obj){
        initComponents();
        String username=(String)obj.get(0);
        txtWelcome.setText("Welcome : "+username);
    }
//   ?>
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodipanel = new javax.swing.JPanel();
        topMenu = new javax.swing.JPanel();
        txtWelcome = new javax.swing.JLabel();
        leftMenu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Notifikasi = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Berita = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Info = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtUsername2 = new javax.swing.JTextField();
        txtUsername1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(127, 208, 41));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 600));

        bodipanel.setBorder(null);
        bodipanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topMenu.setBackground(new java.awt.Color(254, 254, 254));

        txtWelcome.setText("Welcome : ");

        javax.swing.GroupLayout topMenuLayout = new javax.swing.GroupLayout(topMenu);
        topMenu.setLayout(topMenuLayout);
        topMenuLayout.setHorizontalGroup(
            topMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topMenuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtWelcome)
                .addContainerGap(654, Short.MAX_VALUE))
        );
        topMenuLayout.setVerticalGroup(
            topMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topMenuLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(txtWelcome)
                .addContainerGap())
        );

        bodipanel.add(topMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 750, 50));

        leftMenu.setBackground(new java.awt.Color(14, 27, 53));

        jLabel5.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/home.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/notif.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/help.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/news.png")); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout leftMenuLayout = new javax.swing.GroupLayout(leftMenu);
        leftMenu.setLayout(leftMenuLayout);
        leftMenuLayout.setHorizontalGroup(
            leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        leftMenuLayout.setVerticalGroup(
            leftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftMenuLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel5)
                .addGap(102, 102, 102)
                .addComponent(jLabel4)
                .addGap(115, 115, 115)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(77, 77, 77))
        );

        bodipanel.add(leftMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 600));

        mainPanel.setBackground(new java.awt.Color(246, 247, 250));
        mainPanel.setLayout(new java.awt.CardLayout());

        Home.setBackground(new java.awt.Color(231, 229, 227));
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/logo.png")); // NOI18N
        Home.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 28, -1, 55));

        jTextField1.setBackground(new java.awt.Color(231, 229, 227));
        jTextField1.setText("Masukan Nama Tempat");
        jTextField1.setBorder(null);
        jTextField1.setPreferredSize(new java.awt.Dimension(162, 15));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Home.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 260, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/txtfield.png")); // NOI18N
        Home.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, 42));

        jLabel2.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/backg.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Home.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 750, 340));

        mainPanel.add(Home, "home");

        Notifikasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/ring.png")); // NOI18N
        Notifikasi.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, 70));

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Notifikasi.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 550, 50));

        jLabel24.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/ring.png")); // NOI18N
        Notifikasi.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 80, 70));

        jPanel6.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Notifikasi.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 550, 50));

        jLabel25.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/ring.png")); // NOI18N
        Notifikasi.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 80, 70));

        jPanel7.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Notifikasi.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 550, 50));

        jLabel26.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/ring.png")); // NOI18N
        Notifikasi.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 80, 70));

        jPanel8.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Notifikasi.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        mainPanel.add(Notifikasi, "notif");

        Berita.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setText("Judul Berita");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        Berita.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 200, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/shape.png")); // NOI18N
        Berita.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("Judul Berita");
        Berita.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 200, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/shape.png")); // NOI18N
        Berita.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, -1, 40));

        jLabel17.setForeground(new java.awt.Color(254, 254, 254));
        jLabel17.setText("Judul Berita");
        Berita.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 200, 20));

        jLabel19.setForeground(new java.awt.Color(254, 254, 254));
        jLabel19.setText("Judul Berita");
        Berita.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 200, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/shape.png")); // NOI18N
        Berita.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, 40));

        jLabel18.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/shape.png")); // NOI18N
        Berita.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, -1, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/header.png")); // NOI18N
        jLabel21.setText("jLabel21");
        Berita.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/image/2.png")); // NOI18N
        Berita.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/image/4.png")); // NOI18N
        Berita.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/image/1.png")); // NOI18N
        Berita.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/image/3.png")); // NOI18N
        Berita.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        mainPanel.add(Berita, "news");

        Info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/header.png")); // NOI18N
        jLabel20.setText("jLabel20");
        Info.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtUsername2.setBackground(new java.awt.Color(231, 229, 227));
        txtUsername2.setForeground(new java.awt.Color(1, 1, 1));
        txtUsername2.setText("Username");
        txtUsername2.setBorder(null);
        txtUsername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername2ActionPerformed(evt);
            }
        });
        Info.add(txtUsername2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 270, 30));

        txtUsername1.setBackground(new java.awt.Color(231, 229, 227));
        txtUsername1.setForeground(new java.awt.Color(1, 1, 1));
        txtUsername1.setText("Email");
        txtUsername1.setBorder(null);
        txtUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsername1ActionPerformed(evt);
            }
        });
        Info.add(txtUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 270, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Info.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 270, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon("/media/fataelislami/DATA/Linux Download/JavaUI/kirim.png")); // NOI18N
        Info.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        jLabel22.setFont(new java.awt.Font("Abyssinica SIL", 0, 24)); // NOI18N
        jLabel22.setText("Contact US");
        Info.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        mainPanel.add(Info, "Info");

        bodipanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 750, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bodipanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodipanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        CardLayout card =(CardLayout)mainPanel.getLayout();
        card.show(mainPanel,"home");
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        CardLayout card =(CardLayout)mainPanel.getLayout();
        card.show(mainPanel,"notif");
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        CardLayout card =(CardLayout)mainPanel.getLayout();
        card.show(mainPanel,"news");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        CardLayout card =(CardLayout)mainPanel.getLayout();
        card.show(mainPanel,"Info");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"COY");
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtUsername2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername2ActionPerformed

    private void txtUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsername1ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,jLabel13);
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Berita;
    private javax.swing.JPanel Home;
    private javax.swing.JPanel Info;
    private javax.swing.JPanel Notifikasi;
    private javax.swing.JPanel bodipanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel leftMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel topMenu;
    private javax.swing.JTextField txtUsername1;
    private javax.swing.JTextField txtUsername2;
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables
}
